//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace IDbase.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IDbaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IDbaseEntities object using the connection string found in the 'IDbaseEntities' section of the application configuration file.
        /// </summary>
        public IDbaseEntities() : base("name=IDbaseEntities", "IDbaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IDbaseEntities object.
        /// </summary>
        public IDbaseEntities(string connectionString) : base(connectionString, "IDbaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IDbaseEntities object.
        /// </summary>
        public IDbaseEntities(EntityConnection connection) : base(connection, "IDbaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IDtable> IDtables
        {
            get
            {
                if ((_IDtables == null))
                {
                    _IDtables = base.CreateObjectSet<IDtable>("IDtables");
                }
                return _IDtables;
            }
        }
        private ObjectSet<IDtable> _IDtables;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IDtables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIDtables(IDtable iDtable)
        {
            base.AddObject("IDtables", iDtable);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IDbaseModel", Name="IDtable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IDtable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IDtable object.
        /// </summary>
        /// <param name="iDnumber">Initial value of the IDnumber property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static IDtable CreateIDtable(global::System.Int32 iDnumber, global::System.String firstName, global::System.String lastName)
        {
            IDtable iDtable = new IDtable();
            iDtable.IDnumber = iDnumber;
            iDtable.FirstName = firstName;
            iDtable.LastName = lastName;
            return iDtable;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDnumber
        {
            get
            {
                return _IDnumber;
            }
            set
            {
                if (_IDnumber != value)
                {
                    OnIDnumberChanging(value);
                    ReportPropertyChanging("IDnumber");
                    _IDnumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDnumber");
                    OnIDnumberChanged();
                }
            }
        }
        private global::System.Int32 _IDnumber;
        partial void OnIDnumberChanging(global::System.Int32 value);
        partial void OnIDnumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfBirth;
        partial void OnDateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Since
        {
            get
            {
                return _Since;
            }
            set
            {
                OnSinceChanging(value);
                ReportPropertyChanging("Since");
                _Since = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Since");
                OnSinceChanged();
            }
        }
        private Nullable<global::System.DateTime> _Since;
        partial void OnSinceChanging(Nullable<global::System.DateTime> value);
        partial void OnSinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Expire
        {
            get
            {
                return _Expire;
            }
            set
            {
                OnExpireChanging(value);
                ReportPropertyChanging("Expire");
                _Expire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Expire");
                OnExpireChanged();
            }
        }
        private Nullable<global::System.DateTime> _Expire;
        partial void OnExpireChanging(Nullable<global::System.DateTime> value);
        partial void OnExpireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PlaceOfBirth
        {
            get
            {
                return _PlaceOfBirth;
            }
            set
            {
                OnPlaceOfBirthChanging(value);
                ReportPropertyChanging("PlaceOfBirth");
                _PlaceOfBirth = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PlaceOfBirth");
                OnPlaceOfBirthChanged();
            }
        }
        private global::System.String _PlaceOfBirth;
        partial void OnPlaceOfBirthChanging(global::System.String value);
        partial void OnPlaceOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private Nullable<global::System.Boolean> _Sex;
        partial void OnSexChanging(Nullable<global::System.Boolean> value);
        partial void OnSexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Photo
        {
            get
            {
                return StructuralObject.GetValidValue(_Photo);
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.Byte[] _Photo;
        partial void OnPhotoChanging(global::System.Byte[] value);
        partial void OnPhotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Photo2
        {
            get
            {
                return StructuralObject.GetValidValue(_Photo2);
            }
            set
            {
                OnPhoto2Changing(value);
                ReportPropertyChanging("Photo2");
                _Photo2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo2");
                OnPhoto2Changed();
            }
        }
        private global::System.Byte[] _Photo2;
        partial void OnPhoto2Changing(global::System.Byte[] value);
        partial void OnPhoto2Changed();

        #endregion
    
    }

    #endregion
    
}
